### ISSUE TITLE
Poor Pipeline Performance

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#23]
**Completed**

- Downloaded 5 new tracks from BigQuery. One turned out to be a duplicate, so discarded it.

    - Uploaded remaining tracks to GoogleDrive

- Ran these tracks against model trained in compare single model.

     - Tracks still had low False positive rate (~4%)

     - False positives were clumped, not clustered, so shouldn't have appearance of dotted tracks.

- Ran against model parameters in models directory

    - Parameters that I generated locally using train_models

           - Worked identically

    - Parameters that I downloaded from github

          - * 90% false positive rate**

**Implication**

**Model parameters on github are broken**

*To Do*

- Download more tracks for testing

- Train again after fixing Kristina's data

**Comment by bitsofbits** [comment]
@redhog can we close this now?

**Comment by redhog** [comment]
Yes
