### ISSUE TITLE
Accuracy vs AIS coverage

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/vessel-scoring#29]
Accuracy vs AIS coverage - downsample and see what happens
Also try accuracy vs track length

**Comment by davidkroodsma** [comment]
*Density*. We can simulate this by randomly removing points.
 - [ ] Calculate the fishing hours vs. positions per day
 - [ ] See how sensitive the nominal fishing hours is to adjusting the upper limit on time between points.


Changes in satellite coverage over time
- [ ] Look at the ratio of the fishing to non-fishing points for a given part of the ocean between years, 
- [ ] and see if there is any correlation with this to the number of satellites.


Terrestrial fishing vs. satellite fishing
- [ ] First, look at the data and compare fishing effort in terrestrial vs. satellite (for similar distance to shore) (this might not work
