### ISSUE TITLE
Tag initial release

### ISSUE THREAD

**Issue by geowurster** [GlobalFishingWatch/vessel-scoring#31]
For the pipeline we are installing this directly from `master`, which could give us some incomplete changes or features.  I would be much more comfortable installing from tagged releases.  Tag needs to be a real release and not a draft or pre-release so we can use GitHub's [latest release](https://developer.github.com/v3/repos/releases/#get-the-latest-release) API.

**Comment by geowurster** [comment]
@bitsofbits @redhog This is blocking https://github.com/SkyTruth/benthos-pipeline/pull/595.

**Comment by redhog** [comment]
Done here: https://github.com/GlobalFishingWatch/vessel-scoring/tree/release-1.0
