### ISSUE TITLE
Slow transists dataset evaluation

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/vessel-scoring#4]
I have fixed the slow-transits data so that it has the same format as the other datasets and reuploaded it to google drive. Here is the file list:

datasets/slow-transits.json  datasets/slow-transits.measures.npz  datasets/slow-transits.msg  datasets/slow-transits.npz

Please integrate this in your model evaluation

This task is a subtask of https://github.com/SkyTruth/benthos-pipeline/issues/486

**Comment by bitsofbits** [comment]
Completed some time ago.
