### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#41]
@redhog , we've ended up with too many old branches in github and now it's getting hard to find anything. To clean up I propose that we create pull requests for any branches we're actually using and delete the rest. You're of course free to keep as many branches about locally as you like :-)

**Comment by redhog** [comment]
I have cleant up my branches. Could you evaluate yours and close them if they shouldn't actually be merged?

* https://github.com/GlobalFishingWatch/vessel-scoring/pull/42
* https://github.com/GlobalFishingWatch/vessel-scoring/pull/43
* https://github.com/GlobalFishingWatch/vessel-scoring/pull/44

**Comment by bitsofbits** [comment]
@redhog, Looks like all branches now have pull requests, so I'm closing this. Now I need to start evaluating some of those pull requests....
