### ISSUE TITLE
Look into moving MW code into pipeline.

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#46]
The multiwindow models perform much better than the single window models, so we should look into moving those into the pipeline. In addition we should look into adding is_daylight and/or measure_speed into the models as well. See PR#47 for some motivational numbers.

@redhog, how large a project would this be? Are there performance implications from using all those windows?

**Comment by redhog** [comment]
This is already done, as the generic model in the multi-model branch is multi-window:

https://github.com/GlobalFishingWatch/vessel-scoring/blob/multi-model/vessel_scoring/models/Logistic.json

This is what is used if no gear type mapping is supplied to the pipeline.
