### ISSUE TITLE
Tag / Version info to go into Model Descriptions

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#48]
@redhog, please look at https://github.com/GlobalFishingWatch/vessel-scoring/blob/add-model-descriptions/Model%20Descriptions.ipynb and give me some text for pointing readers to the appropriate version / model for the heuristic and generic models.

While you're at it, let me know if you notice any errors in the descriptions or just stuff you don't like.

**Comment by redhog** [comment]
I have updated the notebook above. However, I think something needs to be done with the variable naming in the section here: https://render.githubusercontent.com/view/ipynb?commit=aa6fcc6c843a83dc5174b55f795e6f1276b31ea8&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f476c6f62616c46697368696e6757617463682f76657373656c2d73636f72696e672f616136666363366338343361383364633531373462353566373935653666313237366233316561382f4d6f64656c2532304465736372697074696f6e732e6970796e62&nwo=GlobalFishingWatch%2Fvessel-scoring&path=Model+Descriptions.ipynb&repository_id=53938924#Heuristic-Model

**Comment by bitsofbits** [comment]
I cleaned up the description of the variable naming and the Tag / Version info looks OK to me.
