### ISSUE TITLE
More slow transits

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/vessel-scoring#5]
More MMSI:s with slow transists:

367512170
412420435
416213800
367512180
367512170
367534310
441699000
231030000
224908220
367512510
412430920
416004583
412420875

This task is a subtask of https://github.com/SkyTruth/benthos-pipeline/issues/486

**Comment by redhog** [comment]
@bitsofbits Have these all been added to our dataset? If so, can we close this?

**Comment by bitsofbits** [comment]
It sounds like the slow transit emergency is over, so we can close this. We need more data in general, but not these specific, so yes, we can close this.
