### ISSUE TITLE
Consolidate notebooks

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#53]
Proposal:

* Move all notebooks to `notebooks`

* Prune the notebooks down to:

   - A comparison between models based on compare_with_dal

   - AIS degradation info

   - Model sensitivity to seed 

   - Description of models

   - Revamp the cross validation notebook

@redhog : anything else?

**Comment by redhog** [comment]
What's in the cross validation notebook, how does it differ from the compare_with_dal one?
From what I know the description of models notebook is only on a branch, not on master. We should merge that in.

**Comment by bitsofbits** [comment]
@redhog , I'll take a look at the description of models notebook.  As for cross validation, what that is supposed to do is run the models using different choices of metaparameters and choose the best set. So order, cross, whether to use is_daylight, etc.

**Comment by bitsofbits** [comment]
@redhog , I let this slip for a few days. 

* `Model-Desciptions` is now in master and in this branch.

* I don't think we need to do anything about the cross validation notebook right now, we can just open an issue about it and delete what we have. (We should add a link to the last commit in the issue so we can look at the current code for reference in the future).

* There is currently only `Model-Descriptions` which has some model comparisons, although not as many as the old comparison notebooks. Do you think this enough? It seems like it should be OK, but let me know if you think we need more.

* Can we get rid of `Vessel scoring problematic examples.ipynb`?

* Also need to get rid of `Find_unscaled_data.ipynb`, any objections?
