### ISSUE TITLE
Add offset framework to add_measures

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#61]
It turns out that the windowing discussed in issue: https://github.com/GlobalFishingWatch/rolling_measures/issues/1 , needs to be implemented in add_measures.AddWindowMeasures. The constructor of AddWindowMeasures  needs to take an offset parameter. 

The relevant function is process, and we'll need to tee into three streams one for the start, one for the end. And one for the location where we are looking.

**Comment by redhog** [comment]
@bitsofbits Heyas! I think this works, but I'm unable to test it thoroughly using the whole vessel scoring framework - training the models crashes my laptop (entirely, including the kernel) for some reason.

**Comment by bitsofbits** [comment]
@egil: Thanks. I'll take a look at this tomorrow or Monday when I'm back home.

**Comment by bitsofbits** [comment]
@redhog : I needed to fix a couple of things, but this is running now locally and I pushed the changes up. It does make a noticeable difference, particularly with purse seiners using random forest, although those still aren't great.

**Comment by redhog** [comment]
@bitsofbits Could you run this with an offset of zero? Thast should give _no_ difference what so ever from the old code. Could you make sure this is the case?

**Comment by bitsofbits** [comment]
@redhog : I tried that and my initial result is that there was some difference. I'm working on tracking that down today.
