### ISSUE TITLE
Test LogisticScorer in pipeline

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-scoring#9]
Need to TestLogistic  in pipeline on the bad track time plus some surrounding time to make sure this is a satisfactory fix for bad transits and doesn't break anything else.

**Comment by redhog** [comment]
New tileset: http://alpha-dev.globalfishingwatch.org/viz?workspace=/workspace%3Fid%3D2015-12-new-scoring-6

Closing in favor of https://github.com/SkyTruth/benthos-pipeline/issues/573
